### ISSUE TITLE
Custom number of weeks for chart

### ISSUE THREAD

**Issue by lorezyra** [HCLonely/hexo-calendar#5]
You define the `getCommitData()` [function's input](https://github.com/HCLonely/hexo-calendar/blob/7122b0f42708e19af42108052ad07abc12d79fc7/index.js#L158) here:
https://github.com/HCLonely/hexo-calendar/blob/7122b0f42708e19af42108052ad07abc12d79fc7/index.js#L22

However, there doesn't appear a way to change the default 40 weeks to a different value. Can you update this?

**Comment by HCLonely** [comment]
You can use the `hexo gc -w=10` command to change the number of weeks to 10.

**Comment by lorezyra** [comment]
Thanks, ~~can you add that detail to the [readme](https://github.com/HCLonely/hexo-calendar/blob/master/README.md) file?~~

I see it in the readme now. All good.
